// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamNest.Models
{
    public partial class AuthenticateUserResult
    {
        public int id { get; set; }
        [StringLength(100)]
        public string name { get; set; }
        [StringLength(255)]
        public string email { get; set; }
        [StringLength(50)]
        public string role { get; set; }
        public int? student_id { get; set; }
        public int? instructor_id { get; set; }
        public bool? is_admin { get; set; }
    }
}
