// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamNest.Models
{
    public partial class CreateBranchResult
    {
        [Column("BranchID", TypeName = "decimal(38,0)")]
        public decimal? BranchID { get; set; }
    }
}
