// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamNest.Models
{
    public partial class CreateTrackResult
    {
        [Column("TrackID", TypeName = "decimal(38,0)")]
        public decimal? TrackID { get; set; }
    }
}
