// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExamNest.Models;

public partial class Exam
{
    public int ExamId { get; set; }

    public int CourseId { get; set; }

    public DateTime ExamDate { get; set; }

    public DateTime EndDate { get; set; }
    public virtual Course Course { get; set; }

    public virtual ICollection<ExamSubmission> ExamSubmissions { get; set; } = new List<ExamSubmission>();
    public virtual ICollection<ExamQuestion> ExamQuestions { get; set; }

}