// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExamNest.Models;

public partial class ExamSubmission
{
    public int SubmissionId { get; set; }

    public int ExamId { get; set; }

    public int StudentId { get; set; }

    public DateTime SubmissionDate { get; set; }

    public decimal? Score { get; set; }

    public virtual Exam Exam { get; set; }

    public virtual Student Student { get; set; }

    public virtual ICollection<StudentAnswer> StudentAnswers { get; set; } = new List<StudentAnswer>();
}