// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamNest.Models
{
    public partial class GetCoursesByTrackResult
    {
        public int CourseID { get; set; }
        public int TrackID { get; set; }
        [StringLength(100)]
        public string CourseName { get; set; }
        [StringLength(100)]
        public string TrackName { get; set; }
    }
}
