// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamNest.Models
{
    public partial class GetExamDetailsResult
    {
        public int ExamID { get; set; }
        public int CourseID { get; set; }
        [StringLength(100)]
        public string CourseName { get; set; }
        public DateTime ExamDate { get; set; }
        public int? QuestionCount { get; set; }
    }
}
