// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamNest.Models
{
    public partial class GetExamQuestionListResult
    {
        public int QuestionID { get; set; }
        [StringLength(2147483647)]
        public string QuestionText { get; set; }
        [StringLength(10)]
        public string QuestionType { get; set; }
        public int Points { get; set; }
    }
}
