// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamNest.Models
{
    public partial class GetInstructorsByBranchResult
    {
        public int InstructorID { get; set; }
        public int BranchID { get; set; }
        public int TrackID { get; set; }
        [Column("Instructor Name")]
        [StringLength(100)]
        public string InstructorName { get; set; }
        [StringLength(255)]
        public string Email { get; set; }
        [StringLength(100)]
        public string BranchName { get; set; }
        [StringLength(100)]
        public string TrackName { get; set; }
    }
}
