// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamNest.Models
{
    public partial class GetStudentByIDResult
    {
        public int StudentID { get; set; }
        public int BranchID { get; set; }
        public int TrackID { get; set; }
        [Column("Student Name")]
        [StringLength(100)]
        public string StudentName { get; set; }
        [Column("Student Email")]
        [StringLength(255)]
        public string StudentEmail { get; set; }
        [StringLength(100)]
        public string BranchName { get; set; }
        [StringLength(100)]
        public string TrackName { get; set; }
    }
}
