// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamNest.Models
{
    public partial class GetStudentExamChoiceDetailsResult
    {
        public int QuestionID { get; set; }
        public int ChoiceID { get; set; }
        public string ChoiceLetter { get; set; }
        [StringLength(2147483647)]
        public string ChoiceText { get; set; }
        public bool? IsStudentSelection { get; set; }
        public bool? IsCorrectAnswer { get; set; }
    }
}
