// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamNest.Models
{
    public partial class GetStudentExamAnswerDetailsResult
    {
        public int QuestionID { get; set; }
        [StringLength(2147483647)]
        public string QuestionText { get; set; }
        [StringLength(10)]
        public string QuestionType { get; set; }
        public string StudentAnswer { get; set; }
        public string ModelAnswer { get; set; }
        [StringLength(9)]
        public string ResultStatus { get; set; }
        public int Points { get; set; }
        public int EarnedPoints { get; set; }
    }
}
