// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamNest.Models
{
    public partial class GetStudentExamResultsResult
    {
        public int SubmissionID { get; set; }
        public int ExamID { get; set; }
        public DateTime ExamDate { get; set; }
        public int CourseID { get; set; }
        [StringLength(100)]
        public string CourseName { get; set; }
        [Column("Score", TypeName = "decimal(5,2)")]
        public decimal? Score { get; set; }
        public DateTime SubmissionDate { get; set; }
    }
}
