// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExamNest.Models;

public partial class QuestionBank
{
    public int QuestionId { get; set; }

    public int CourseId { get; set; }

    public string QuestionText { get; set; }

    public string QuestionType { get; set; }

    public string ModelAnswer { get; set; }

    public int Points { get; set; }

    public virtual ICollection<Choice> Choices { get; set; } = new List<Choice>();

    public virtual Course Course { get; set; }

    public virtual ICollection<StudentAnswer> StudentAnswers { get; set; } = new List<StudentAnswer>();
    public virtual ICollection<ExamQuestion> ExamQuestions { get; set; }

}