// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExamNest.Models;

public partial class Student
{
    public int StudentId { get; set; }

    public int BranchId { get; set; }

    public int TrackId { get; set; }

    public string UserId { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual ICollection<ExamSubmission> ExamSubmissions { get; set; } = new List<ExamSubmission>();

    public virtual Track Track { get; set; }

    public virtual User User { get; set; }
}