// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExamNest.Models;

public partial class StudentAnswer
{
    public int SubmissionId { get; set; }

    public int QuestionId { get; set; }

    public string StudentAnswer1 { get; set; }

    public virtual QuestionBank Question { get; set; }

    public virtual ExamSubmission Submission { get; set; }
}