// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExamNest.Models
{
    public partial class SubmitExamAnswersResult
    {
        public int? SubmissionID { get; set; }
        public int? ExamID { get; set; }
        public int? StudentID { get; set; }
        public DateTime SubmissionDate { get; set; }
        public int? AnsweredQuestionsCount { get; set; }
    }
}
